### PR TITLE
Fix macOS (darwin) Build

### PR DESCRIPTION
**Pull request by bsvec**
This PR fixes an issue where on macOS (darwin) the gst library would fail to build with the following error:
```
common.go:185:29: constant -1 overflows uint64
```

The constant `GST_CLOCK_TIME_NONE` is defined to be `-1` in C code.  The golang code in the original `common.go` tries to assign this to a variable of type `uint64`.  This works on linux but not darwin, which is why you see the error above.

On darwin, changing the type to an int64 allows the build to work but then it does NOT work on linux, stating that the value 2^64 overflows int64.  

So what I've done here is to use golang conditional compilation to make it use `uint64` on linux and `int64` on darwin.  There doesn't appear to be a way to build conditional logic WITHIN a file -- I couldn't find a way to say the equivalent of "if its linux do this but if its darwin do that".  Conditional compilation in go seems to be based at the file level and it can either use tags or filename suffixes.  I chose the filename suffix route.  So now there's a `common_linux.go` file and a `common_darwin.go` in addition to `common.go`.  The definition of `CLOCK_TIME_NONE` has been removed from `common.go` and put into the other two files.  `common_linux.go` has the `uint64` version and `common_darwin.go` has the `int64` version.

### CODE REVIEW

**Review by burrows — COMMENTED** [review]
Could you have the arch specific files just define the CLOCK_TIME_NONE constant?

**Comment by bsvec** [comment]
@burrows I tried that, but I was getting errors that I didn't understand.  Worth another look.

**Comment by bsvec** [comment]
@burrows Ok -- I think I have it working that way now.  I forgot to include the C header imports in cgo code before.  Much cleaner this way.

**Review by burrows — APPROVED** [review]
Nice!

**Pull request merged**
